runtime: nodejs12


handlers:
  - url: /(.*\.(gif|svg|png)(|\.map))$
    static_files: cricVis/assets/images\1
    upload: cricVis/(.*)(|\.map)
  - url: /.*
    static_files: cricVis/index.html
    upload: cricVis/.*